import type { Metadata } from "next";
import { Geist, Geist_Mono,Vazirmatn } from "next/font/google";
import "./globals.css";
const vazirmatn = Vazirmatn({
  variable: "--font-vazirmatn",
  subsets: ["latin",],
  weight: ['100','200','300',"400", "700"],
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body
        className={`${vazirmatn.variable} ${vazirmatn.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
