import type { Metadata } from "next";
import { Geist, Geist_Mono, Vazirmatn } from "next/font/google";
import "./globals.css";
import Link from "next/link";
const vazirmatn = Vazirmatn({
  variable: "--font-vazirmatn",
  subsets: ["latin",],
  weight: ['100', '200', '300', "400", "700"],
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body
        className={`${vazirmatn.variable} ${vazirmatn.variable} antialiased`}
      >
        {children}
        <hr className="my-8 border-gray-700" />
        <Link href="/">صفحه اصلی</Link>
        <footer className="text-center text-gray-500 p-4">
          ساخته شده با ❤️ توسط{" "}
          <span>Ali Baghernia</span>
        </footer>
      </body>
    </html>
  );
}
